### ISSUE TITLE
Error in some numpy datatype

### ISSUE THREAD

**Issue by MetalnAlloys** [emerald-geomodelling/disco-tif#12]
Got the following error after deploying from the latest code:

Function call I made:
```python
cmap_methods = ['pseudo_linear', 'pseudo_hist_norm']
 
for cmap_method in cmap_methods:
        processed_geotiff = process_sb_tiff.make_rgba_tiff_from_single_Band(
                    geotiff_path,
                    cmap_method=cmap_method,
        )
```

Traceback:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/histograms.py", line 419, in _get_bin_edges
    n_equal_bins = operator.index(bins)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/app/mapserver/rasterserver/views.py", line 50, in process
    new_geotiffs = generate_rgba_geotiffs(original_raster_path)
  File "/app/mapserver/rasterserver/update_config.py", line 137, in generate_rgba_geotiffs
    processed_geotiff = process_sb_tiff.make_rgba_tiff_from_single_Band(
  File "/usr/local/lib/python3.10/dist-packages/disco_tif/process_sb_tiff.py", line 397, in make_rgba_tiff_from_single_Band
    data_breaks = make_percentile_array(data_min_max=data_min_max,
  File "/usr/local/lib/python3.10/dist-packages/disco_tif/process_sb_tiff.py", line 227, in make_percentile_array
    ax.hist(no_dum_data, bins=min(abs_min_max[1]-abs_min_max[0], 100))
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_axes.py", line 6862, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/histograms.py", line 780, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/histograms.py", line 421, in _get_bin_edges
    raise TypeError(
TypeError: `bins` must be an integer, a string, or an array

**Comment by burningsage** [comment]
fixed. made sure that bins was an int.
